# Generated by Django 5.1.1 on 2024-09-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="", verbose_name="Image"),
        ),
    ]
