# Generated by Django 5.1.1 on 2024-09-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_blogpost_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="posts", verbose_name="Image"
            ),
        ),
    ]
