# Generated by Django 5.1.1 on 2024-09-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
