# Generated by Django 5.1.1 on 2024-09-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
